version: "3.7"
services:
  spring-boot-app:
    build:
      context: ./backend/spring-boot-backend/
      dockerfile: Dockerfile
    image: product-backend-app
    container_name: spring-boot-backend
    ports:
      - "8080:8080"
    networks:
      - app-network  
  product-frontend:
    image: pwalendz81/front-medicine-app2.0
    container_name: front-end-app
    ports:
      - "84:80"
    depends_on:
    - spring-boot-app
    networks:
      - app-network
networks:
  app-network: